tools:
    php_cs_fixer: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: true
    php_cpd: true
    php_analyzer:
        filter:
            excluded_paths: ["tests/*"]
    sensiolabs_security_checker: true
    php_pdepend: true
    external_code_coverage:
        timeout: 1200
