language: php

php:
  - 5.6
  - 7.0

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer selfupdate
  - composer install

script:
  - phpcs --ignore=/vendor/*,/tests/Resources/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .

notifications:
  email: "nicolasbastien.pro@gmail.com"
